export type Quest = {
  id: string;
  title: string;
  location: string;
  action: string;
  tooltip: string;
  reward: number;
};

export type PageGuide = {
  pathname: string;
  emoji: string;
  mission: string;
  completionBadge: string;
  badgeEmoji: string;
  color: string;       // kept for reference
  gradient: string;    // inline CSS gradient used directly in style props
  quests: Quest[];
};

export const pageGuides: PageGuide[] = [
  {
    pathname: "/dashboard",
    emoji: "🗺️",
    mission: "Explore your command center — understand your lab's health",
    completionBadge: "Navigator",
    badgeEmoji: "🗺️",
    color: "from-violet-600 to-indigo-600",
    gradient: "linear-gradient(135deg, #7c3aed, #4338ca)",
    quests: [
      {
        id: "dash-1",
        title: "Check Setup Progress",
        location: "📍 Top row → first stat card (left)",
        action: "👉 Read your overall setup completion percentage",
        tooltip: "Your setup score lives here",
        reward: 15,
      },
      {
        id: "dash-2",
        title: "Read the Compliance Health",
        location: "📍 Top row → third stat card (right)",
        action: "👉 Note whether you have any critical blockers",
        tooltip: "Red means action needed immediately",
        reward: 15,
      },
      {
        id: "dash-3",
        title: "Open the Roadmap module",
        location: "📍 Module grid → Roadmap card (top-left area)",
        action: "👉 Click the Roadmap card to open your 60-day plan",
        tooltip: "Click the Roadmap card to go there",
        reward: 20,
      },
      {
        id: "dash-4",
        title: "Identify all 9 modules",
        location: "📍 Module grid → 9 coloured icon cards",
        action: "👉 Read every module card name without clicking",
        tooltip: "Nine modules power your entire setup",
        reward: 10,
      },
    ],
  },
  {
    pathname: "/dashboard/guide",
    emoji: "📖",
    mission: "Master Indian lab regulations — read before you build",
    completionBadge: "Regulation Scholar",
    badgeEmoji: "📖",
    color: "from-emerald-600 to-teal-600",
    gradient: "linear-gradient(135deg, #059669, #0d9488)",
    quests: [
      {
        id: "guide-1",
        title: "Switch to the Quick Guide tab",
        location: "📍 Top of page → tab bar → 'Quick Guide'",
        action: "👉 Click the Quick Guide tab and scan all 6 cards",
        tooltip: "Six cards, six essential topics",
        reward: 10,
      },
      {
        id: "guide-2",
        title: "Read the BMW Waste colour coding",
        location: "📍 Quick Guide tab → last card (BMW Waste)",
        action: "👉 Memorise the 4 bag colours and their waste types",
        tooltip: "Inspectors test this — know it cold",
        reward: 20,
      },
      {
        id: "guide-3",
        title: "Open the Comprehensive Guide",
        location: "📍 Tab bar → 'Comprehensive Guide' tab",
        action: "👉 Click the tab and expand the CEA 2010 accordion section",
        tooltip: "CEA is the law governing your lab",
        reward: 15,
      },
      {
        id: "guide-4",
        title: "Find your staffing requirements",
        location: "📍 Comprehensive Guide → Section 4: Staffing & Personnel",
        action: "👉 Expand section 4 and find minimum qualifications for your lab type",
        tooltip: "Wrong hires = CEA violation",
        reward: 20,
      },
    ],
  },
  {
    pathname: "/dashboard/roadmap",
    emoji: "🗓️",
    mission: "Build your 60-day lab launch plan — every task counts",
    completionBadge: "Strategist",
    badgeEmoji: "🗓️",
    color: "from-blue-600 to-cyan-600",
    gradient: "linear-gradient(135deg, #2563eb, #0891b2)",
    quests: [
      {
        id: "road-1",
        title: "Complete the setup form",
        location: "📍 Top of page → onboarding form (first visit only)",
        action: "👉 Fill in lab type, state, district, city, and budget — then submit",
        tooltip: "This personalises your entire roadmap",
        reward: 30,
      },
      {
        id: "road-2",
        title: "Read the progress bar",
        location: "📍 Below the form → Day X / 60 progress bar",
        action: "👉 Note your current day count and estimated launch date",
        tooltip: "Your 60-day countdown starts here",
        reward: 10,
      },
      {
        id: "road-3",
        title: "Find a Critical priority task",
        location: "📍 Phase 1 cards → look for red 'Critical' badge",
        action: "👉 Read what a Critical task requires and mark it complete",
        tooltip: "Critical tasks block all later phases",
        reward: 25,
      },
      {
        id: "road-4",
        title: "Read all 5 phase titles",
        location: "📍 Scroll down → 5 phase section headers",
        action: "👉 Identify Phase 1 through Phase 5 and their week ranges",
        tooltip: "Five phases, 60 days, one launch",
        reward: 10,
      },
    ],
  },
  {
    pathname: "/dashboard/licensing",
    emoji: "📋",
    mission: "Apply for your first mandatory license — paperwork is power",
    completionBadge: "First Filing",
    badgeEmoji: "📋",
    color: "from-orange-600 to-amber-500",
    gradient: "linear-gradient(135deg, #ea580c, #f59e0b)",
    quests: [
      {
        id: "lic-1",
        title: "Filter by Mandatory licenses",
        location: "📍 Left panel → category filter buttons below the search bar",
        action: "👉 Click 'Mandatory' to see only licenses required by law",
        tooltip: "Mandatory first — optional later",
        reward: 10,
      },
      {
        id: "lic-2",
        title: "Search for CEA License",
        location: "📍 Left panel → search bar at the top",
        action: "👉 Type 'CEA' and read the document requirements shown",
        tooltip: "CEA is your lab's operating permit",
        reward: 15,
      },
      {
        id: "lic-3",
        title: "Apply for your first license",
        location: "📍 Any license card → 'Apply' button",
        action: "👉 Click Apply, select your state, and submit to add to tracker",
        tooltip: "Select your state — rules differ by state",
        reward: 30,
      },
      {
        id: "lic-4",
        title: "Expand a license in the Tracker",
        location: "📍 Right panel → License Tracker → any applied license",
        action: "👉 Click to expand and review the document checklist",
        tooltip: "Tracker lives on the right side panel",
        reward: 15,
      },
    ],
  },
  {
    pathname: "/dashboard/equipment",
    emoji: "⚙️",
    mission: "Plan your lab from bench to analyzer — before you spend a rupee",
    completionBadge: "Lab Planner",
    badgeEmoji: "⚙️",
    color: "from-slate-600 to-zinc-600",
    gradient: "linear-gradient(135deg, #475569, #52525b)",
    quests: [
      {
        id: "equip-1",
        title: "Run AI equipment recommendations",
        location: "📍 'Patho.ai Insight' panel → Generate button",
        action: "👉 Enter your test menu and click Generate for AI recommendations",
        tooltip: "AI finds equipment you might miss",
        reward: 25,
      },
      {
        id: "equip-2",
        title: "Browse the 4 equipment categories",
        location: "📍 Equipment categories section → 4 tabs or sections",
        action: "👉 Scroll through Core Analyzers, Phlebotomy, Lab Essentials, and IT",
        tooltip: "Four categories cover every instrument",
        reward: 10,
      },
      {
        id: "equip-3",
        title: "Update an equipment status",
        location: "📍 Your Equipment List → status stepper on any item",
        action: "👉 Advance any item one step forward (e.g. Planning → Ordered)",
        tooltip: "Five stages: plan to fully integrated",
        reward: 20,
      },
      {
        id: "equip-4",
        title: "Check vendor discounts",
        location: "📍 Vendor Marketplace section → vendor discount cards",
        action: "👉 Find the best discount and note the vendor name",
        tooltip: "Pre-negotiated rates save lakhs",
        reward: 15,
      },
    ],
  },
  {
    pathname: "/dashboard/staff",
    emoji: "👥",
    mission: "Build your compliant dream team — every role is a compliance gate",
    completionBadge: "HR Hero",
    badgeEmoji: "👥",
    color: "from-pink-600 to-rose-600",
    gradient: "linear-gradient(135deg, #db2777, #e11d48)",
    quests: [
      {
        id: "staff-1",
        title: "Add your first staff member",
        location: "📍 Add Staff form → fill all fields → Submit",
        action: "👉 Add a Pathologist with their qualification and salary",
        tooltip: "Pathologist is your most critical hire",
        reward: 30,
      },
      {
        id: "staff-2",
        title: "Check the Onboarding Funnel",
        location: "📍 Stats cards row → first card (Onboarding Funnel)",
        action: "👉 Note how many of 5 core positions are filled",
        tooltip: "Five roles to fill before go-live",
        reward: 10,
      },
      {
        id: "staff-3",
        title: "Update a training status",
        location: "📍 Staff table → Training Status column → any staff row",
        action: "👉 Click Edit on a staff member and update their training status",
        tooltip: "Training must be certified before launch",
        reward: 20,
      },
      {
        id: "staff-4",
        title: "Find all 4 mandatory trainings",
        location: "📍 Mandatory Training section → list of 4 trainings",
        action: "👉 Read BMW, Infection Control, Fire Safety, and Needle Stick Protocol",
        tooltip: "All four are required by law",
        reward: 10,
      },
    ],
  },
  {
    pathname: "/dashboard/nabl",
    emoji: "🏅",
    mission: "Start your NABL journey — India's gold standard for lab quality",
    completionBadge: "Quality Seeker",
    badgeEmoji: "🏅",
    color: "from-yellow-600 to-amber-600",
    gradient: "linear-gradient(135deg, #ca8a04, #d97706)",
    quests: [
      {
        id: "nabl-1",
        title: "Check your readiness score",
        location: "📍 Tab 1: Overview → large percentage banner at top",
        action: "👉 Read your current % score and note which clauses are weakest",
        tooltip: "Score updates live as you check items",
        reward: 15,
      },
      {
        id: "nabl-2",
        title: "Complete 5 checklist items",
        location: "📍 Tab 2: Document Checklist → sections A through M",
        action: "👉 Tick off 5 items you've already done (or plan to do first)",
        tooltip: "200+ items — start with Section A",
        reward: 30,
      },
      {
        id: "nabl-3",
        title: "Log a proficiency test",
        location: "📍 Tab 3: Tests & Audits → EQAS / Proficiency Testing table",
        action: "👉 Add an EQAS entry with provider name and test type",
        tooltip: "No EQAS = no NABL accreditation",
        reward: 25,
      },
      {
        id: "nabl-4",
        title: "Review the NABL timeline",
        location: "📍 Tab 4: NABL Timeline → 5-phase summary table",
        action: "👉 Note the total duration and plan your accreditation start date",
        tooltip: "12–18 months total — start now",
        reward: 10,
      },
    ],
  },
  {
    pathname: "/dashboard/compliance",
    emoji: "🚦",
    mission: "Clear every blocker and earn your green Go-Live flag",
    completionBadge: "Compliance Champion",
    badgeEmoji: "🚦",
    color: "from-red-600 to-rose-600",
    gradient: "linear-gradient(135deg, #dc2626, #e11d48)",
    quests: [
      {
        id: "comp-1",
        title: "Initialize your compliance gates",
        location: "📍 Top of page → 'Initialize Gates' button",
        action: "👉 Click it, select your state, and seed your gates",
        tooltip: "Must do this first — gates are state-specific",
        reward: 25,
      },
      {
        id: "comp-2",
        title: "Update a regulatory gate status",
        location: "📍 Left column → Regulatory Compliance Gates",
        action: "👉 Click the status dropdown on any gate and update it",
        tooltip: "Status saves instantly — no submit needed",
        reward: 20,
      },
      {
        id: "comp-3",
        title: "Expand a gate's detail view",
        location: "📍 Any gate card → 'Expand' or chevron button",
        action: "👉 Open a gate to see its full document checklist",
        tooltip: "Every gate has a hidden checklist inside",
        reward: 15,
      },
      {
        id: "comp-4",
        title: "Run Compliance Validation",
        location: "📍 Bottom of page → 'Run Validation' button",
        action: "👉 Click and wait — your AI compliance score appears",
        tooltip: "Score tells you exactly where to focus",
        reward: 30,
      },
    ],
  },
  {
    pathname: "/dashboard/documents",
    emoji: "📄",
    mission: "Generate and validate your regulatory documents — paperwork done right",
    completionBadge: "Doc Master",
    badgeEmoji: "📄",
    color: "from-sky-600 to-blue-600",
    gradient: "linear-gradient(135deg, #0284c7, #2563eb)",
    quests: [
      {
        id: "docs-1",
        title: "Select a document type to generate",
        location: "📍 Generate tab → 3 document type cards",
        action: "👉 Click the CEA Application card (blue) to open the form",
        tooltip: "CEA Application is your most urgent doc",
        reward: 10,
      },
      {
        id: "docs-2",
        title: "Generate your first document",
        location: "📍 Generate form → fill fields → 'Generate Document' button",
        action: "👉 Complete all required fields and click Generate to download",
        tooltip: "Download saves as a .docx file",
        reward: 30,
      },
      {
        id: "docs-3",
        title: "Upload a document for AI validation",
        location: "📍 AI Validate tab → 'Validate Document' sub-tab → upload zone",
        action: "👉 Drag and drop a PDF or Word doc, select its type, and validate",
        tooltip: "AI finds errors before the inspector does",
        reward: 25,
      },
      {
        id: "docs-4",
        title: "Run a Gap Analysis",
        location: "📍 AI Validate tab → 'Gap Analysis' sub-tab",
        action: "👉 Select your license type, state, and list docs you have",
        tooltip: "Tells you exactly what's missing",
        reward: 20,
      },
    ],
  },
  {
    pathname: "/dashboard/operations",
    emoji: "🧪",
    mission: "Process your first sample from collection to delivery",
    completionBadge: "Lab Operator",
    badgeEmoji: "🧪",
    color: "from-teal-600 to-cyan-600",
    gradient: "linear-gradient(135deg, #0d9488, #0891b2)",
    quests: [
      {
        id: "ops-1",
        title: "Add your first sample order",
        location: "📍 Add Sample form → Patient Name + Tests → Add Order",
        action: "👉 Enter a patient name, select at least one test, and submit",
        tooltip: "New orders start at 'Collected' status",
        reward: 25,
      },
      {
        id: "ops-2",
        title: "Advance a sample to Testing",
        location: "📍 Sample orders table → Action dropdown on any row",
        action: "👉 Click the action dropdown and move the order to 'Testing'",
        tooltip: "Click the dropdown — not the status badge",
        reward: 20,
      },
      {
        id: "ops-3",
        title: "Complete the full workflow",
        location: "📍 Orders table → advance same order through all stages",
        action: "👉 Move any order all the way from 'Testing' to 'Delivered'",
        tooltip: "Five stages: Collected → Delivered",
        reward: 35,
      },
      {
        id: "ops-4",
        title: "Read your TAT indicators",
        location: "📍 Orders table → TAT column on each row",
        action: "👉 Identify a green, amber, and red TAT entry (if available)",
        tooltip: "Red TAT = investigate immediately",
        reward: 10,
      },
    ],
  },
];
